remote_theme: just-the-docs/just-the-docs@v0.10.0
title: NeSy Diagnostics
description: Neuro-Symbolic Diagnostic Assistance Framework
color_scheme: dark
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
plugins:
  - jekyll-remote-theme
exclude: [vendor]
