remote_theme: pages-themes/architect@v0.2.0
title: NeSy Diagnostics
description: Neuro-Symbolic Diagnostic Assistance Framework

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude: [vendor]
